version: '3.8'

services:

  kch-api:
    build:
      context: ./kch-questions
      dockerfile: Dockerfile
    container_name: kch-fastapi
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PYTHONPATH: /app
    ports:
      - "8000:8000"                 # host → contenedor
    volumes:
      - ./kch-questions:/app        # Para desarrollo con hot reload
    restart: unless-stopped
    networks:
      - optimroute
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
